name: "Conftest"
description: "Write tests against structured configuration data using Open Policy Agent"
author: "Gareth Rushgrove"
branding:
  icon: "check"
  color: "green"
inputs: 
  files:
    description: "Files for Conftest to test"
    required: true
  policy:
    description: "Where to find the policy folder or file"
    default: "policy"
  namespace:
    description: "The Rego namespace to use for testing"
    default: "main"
  output:
    description: "Output format for results"
    default: "stdout"
runs:
  using: 'docker'
  image: 'docker://instrumenta/conftest:latest'
  entrypoint: sh
  args:
  - -c
  - conftest test -o ${{ inputs.output }} -p ${{ inputs.policy }} --namespace ${{ inputs.namespace }} ${{ inputs.files }} 
